### ISSUE TITLE
Line grouping doesn't seem to work

### ISSUE THREAD

**Issue by nanocryk** [DevinR528/cargo-sort-ck#27]
I'm trying to run `cargo sort -g` on this Cargo.toml :
https://github.com/PureStake/moonbeam/blob/master/node/cli/Cargo.toml

However it seems to completely ignore the groupings/newlines.
It is also not idempotent as running the command multiple times in a row keeps giving different outputs (no longer changes after 3 steps for this TOML).

Finally, it reorder lines only containing comments by looking at the text of the comment as if it was a key name. While it could make sense for a commented entry, it prevents to use comments to name each group.

**Comment by DevinR528** [comment]
Ok so although this behavior is REALLY odd it does seem "correct" (the `--group` thing is kinda just a heuristic or a weak best effort).

Although I will look into why items seem to migrate up groups, that does seem wrong.

> Finally, it reorder lines only containing comments by looking at the text of the comment as if it was a key name. While it could make sense for a commented entry, it prevents to use comments to name each group.

Do you have an example of this?

The main problem when doing anything with whitespace/comments is that you have to either associate it with the thing before or the thing after, and  you end up guessing what the meaning is that's why you get weird groups like
```toml
log = "0.4.8"
structopt = "0.3.8"
parity-scale-codec = '2.2'

sp-core= ""
sc-cli = ""
sc-service= ""
sc-tracing = ""
sp-runtime = ""
sc-telemetry = ""
frame-benchmarking-cli = ""
try-runtime-cli = ""
```

turning into 

```toml
log = "0.4.8"
parity-scale-codec = '2.2'
structopt = "0.3.8"
frame-benchmarking-cli = ""
sc-cli = ""
sc-service = ""
sc-telemetry= ""
sc-tracing = ""

sp-core = ""
sp-runtime = ""
try-runtime-cli = ""
```
