### ISSUE TITLE
TOML parser throws error if dependencies are divided by newline character

### ISSUE THREAD

**Issue by piotr-roslaniec** [DevinR528/cargo-sort-ck#3]
I presume this is intended behavior. I decided to document it in this issue as a reference. Please close it per your consideration.

Given example `Cargo.toml`:
```toml
[dependencies]
dirs = "1.0.2"

mio = "0.6"
```

Running `cargo-sort-ck` will output unexpected error:
```
Failure: TOML parse error: Invalid token in table, found "\'\\n\' or \'\\r\\n\'"
```

Given fixed example:
```toml
[dependencies]
dirs = "1.0.2"
mio = "0.6"
```

Running `cargo-sort-ck` will output:
```
Success: dependencies are sorted for "<redacted>/Cargo.toml"
```

**Comment by DevinR528** [comment]
Yea it is, my thinking is during development you can do whatever in the Cargo.toml file but since this tool will mostly be used at the end of dev that everything should be cleaned up by then. If you want groupings you could always use comments:
```toml
[dependencies]
# group one
dirs = "1.0.2"
# group two
mio = "0.6"
```
