### ISSUE TITLE
Reorder corrupted with comments

### ISSUE THREAD

**Issue by darwin67** [DevinR528/cargo-sort-ck#8]
Looks like if there are comments in Cargo.toml, sorting doesn't work as expected.

Original
```
[dependencies]
actix-web = "2.0"               # Actix web
actix-rt = "1.1"                # Actix runtime
actix-identity = "0.2"          # Identity
serde = "1.0"                   # serialization
serde_json = "1.0"              # serialization for JSON
log = "0.4"                     # logging
env_logger = "0.7"              # logging
derive_more = "0.99"
futures = "0.3"                 # async
lazy_static = "1.4"             # runtime const evaluation
jsonschema = "0.3"              # JSON schema
rand = "0.7.3"                  # random value generator
uuid = { version = "0.8", features = ["v4"] } # UUID

argonautica = "0.2"  # argon2 password hashing
hmac = "0.9.0"       # for api token hashing
sha2 = "0.9.1"       # for api token hashing
hex = "0.4.2"        # for encoding the bytes from hmac to a postgres TEXT field

diesel = { version = "1.4.4", features = ["postgres", "chrono", "r2d2", "serde_json"] } # Database
chrono = { version = "0.4.11", features = ["serde"] } # time
dotenv = "0.15.0"                                     # environment variables
r2d2 = "0.8"                                          # Database pooling
diesel_migrations = "1.4"       # Embedding database migration
```

Print sort attempt
```
❯ cargo sort-ck -p
[dependencies]
# Actix runtime
actix-identity = "0.2"          # Actix web
actix-rt = "1.1"                actix-web = "2.0"               # UUID

argonautica = "0.2"  # Database
chrono = { version = "0.4.11", features = [ "serde" ] } # logging
derive_more = "0.99"
# for encoding the bytes from hmac to a postgres TEXT field

diesel = { version = "1.4.4", features = [ "postgres", "chrono", "r2d2", "serde_json" ] } # Database pooling
diesel_migrations = "1.4"       # time
dotenv = "0.15.0"                                     # logging
env_logger = "0.7"              futures = "0.3"                 # for api token hashing
hex = "0.4.2"        # argon2 password hashing
hmac = "0.9.0"       # runtime const evaluation
jsonschema = "0.3"              # async
lazy_static = "1.4"             # serialization for JSON
log = "0.4"                     # environment variables
r2d2 = "0.8"                                          # JSON schema
rand = "0.7.3"                  # Identity
serde = "1.0"                   # serialization
serde_json = "1.0"              # for api token hashing
sha2 = "0.9.1"       # random value generator
uuid = { version = "0.8", features = [ "v4" ] } # Embedding database migration
```

**Comment by DevinR528** [comment]
Thanks for the report!

The problem here is somewhat related to #7, the token tree cannot assume a relationship between sibling nodes/tokens. Put another way, the way I designed the formatting rules and walking the token tree structure (and comments and whitespace since they are not strictly defined) it's hard/impossible to make assumptions about which comment belongs to which item (key/value, header, etc.), this also applies to whitespace.

<details>
<summary>Part of the tree made from your toml</summary>

```
Root@[0; 1208)
  Table@[0; 1208)
    Heading@[0; 15)
      OpenBrace@[0; 1) "["
      Ident@[1; 13) "dependencies"
      CloseBrace@[13; 14) "]"
      Whitespace@[14; 15) "\n"
    KeyValue@[15; 47)
      Key@[15; 24)
        Ident@[15; 24) "actix-web"
      Whitespace@[24; 25) " "
      Equal@[25; 26) "="
      Whitespace@[26; 27) " "
      Value@[27; 32)
        Str@[27; 32)
          DoubleQuote@[27; 28) "\""
          Ident@[28; 31) "2.0"
          DoubleQuote@[31; 32) "\""
      Whitespace@[32; 47) "               "
    Comment@[47; 59)
      Hash@[47; 48) "#"
      CommentText@[48; 58) " Actix web"
      Whitespace@[58; 59) "\n"
    KeyValue@[59; 91)
      Key@[59; 67)
        Ident@[59; 67) "actix-rt"
      Whitespace@[67; 68) " "
```
</details>

<details>
<summary>The sorted version</summary>

```
Root@[0; 1208)
  Table@[0; 1208)
    Heading@[0; 15)
      OpenBrace@[0; 1) "["
      Ident@[1; 13) "dependencies"
      CloseBrace@[13; 14) "]"
      Whitespace@[14; 15) "\n"
    Comment@[15; 31)
      Hash@[15; 16) "#"
      CommentText@[16; 30) " Actix runtime"
      Whitespace@[30; 31) "\n"
    KeyValue@[31; 63)
      Key@[31; 45)
        Ident@[31; 45) "actix-identity"
      Whitespace@[45; 46) " "
      Equal@[46; 47) "="
      Whitespace@[47; 48) " "
      Value@[48; 53)
        Str@[48; 53)
          DoubleQuote@[48; 49) "\""
          Ident@[49; 52) "0.2"
          DoubleQuote@[52; 53) "\""
      Whitespace@[53; 63) "          "
    Comment@[63; 75)
      Hash@[63; 64) "#"
      CommentText@[64; 74) " Actix web"
      Whitespace@[74; 75) "\n"
    KeyValue@[75; 107)
      Key@[75; 83)
        Ident@[75; 83) "actix-rt"
      Whitespace@[83; 84) " "
      Equal@[84; 85) "="
      Whitespace@[85; 86) " "
      Value@[86; 91)
        Str@[86; 91)
          DoubleQuote@[86; 87) "\""
          Ident@[87; 90) "1.1"
          DoubleQuote@[90; 91) "\""
      Whitespace@[91; 107) "                "
```
</details>

I'm looking at [the key/value sort function](https://github.com/DevinR528/toml-parse/blob/master/src/sort/mod.rs#L149) to see if I could keep the `KeyValue` and `Comment` nodes together. The problem I think I will run into is this

```toml
[header]
key1 = "value"        # side comment for key1
# above comment for key2
key2 = "value"
```

**Comment by DevinR528** [comment]
Ok I've gotten it to 
```toml
[dependencies]
actix-identity = "0.2"          # Identity
actix-rt = "1.1"                # Actix runtime
actix-web = "2.0"               # Actix web
argonautica = "0.2"  # argon2 password hashing
chrono = { version = "0.4.11", features = [ "serde" ] } # time
derive_more = "0.99"
diesel = { version = "1.4.4", features = [ "postgres", "chrono", "r2d2", "serde_json" ] } # Database
diesel_migrations = "1.4"       # Embedding database migrationdotenv = "0.15.0"                                     # environment variables
env_logger = "0.7"              # logging
futures = "0.3"                 # async
hex = "0.4.2"        # for encoding the bytes from hmac to a postgres TEXT field

hmac = "0.9.0"       # for api token hashing
jsonschema = "0.3"              # JSON schema
lazy_static = "1.4"             # runtime const evaluation
log = "0.4"                     # logging
r2d2 = "0.8"                                          # Database pooling
rand = "0.7.3"                  # random value generator
serde = "1.0"                   # serialization
serde_json = "1.0"              # serialization for JSON
sha2 = "0.9.1"       # for api token hashing
uuid = { version = "0.8", features = [ "v4" ] } # UUID
```
Notice `diesel_migrations` because of not having a `\n` after it breaks the `dotenv = "0.15.0"`. Does this actually have a new line at the end of the table? Otherwise I think you helped me get the comments working much more reliablie thanks.
