### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by caass** [DevinR528/cargo-sort-ck#9]
Hello! Very cool tool. Currently trying to use it and getting an index out of range error.

<details><summary>Stack trace</summary>
<p>

```sh
❯ RUST_BACKTRACE=full cargo sort-ck
thread 'main' panicked at 'index 36 out of range for slice of length 29', /Users/casscool/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-parse-0.2.9/src/sort/mod.rs:188:26
stack backtrace:
   0:        0x10fe2e96e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h24bb64d98a7e25d6
   1:        0x10fe4b82c - core::fmt::write::h8fdc9cddb01cd8b2
   2:        0x10fe2c069 - std::io::Write::write_fmt::hcc3030013983bab6
   3:        0x10fe305c5 - std::panicking::default_hook::{{closure}}::h95817712c5ff0736
   4:        0x10fe30302 - std::panicking::default_hook::h34e085f4e0b1062d
   5:        0x10fe30b25 - std::panicking::rust_panic_with_hook::haf571858f996ac45
   6:        0x10fe306f2 - rust_begin_unwind
   7:        0x10fe5353f - core::panicking::panic_fmt::h11676ba6a846d9f4
   8:        0x10fe535a6 - core::slice::slice_index_len_fail::h501e6942b0a84a54
   9:        0x10fdc3c54 - toml_parse::sort::sort_toml_items::h45f2a25ab7d9b338
  10:        0x10fda3727 - cargo_sort_ck::check_toml::hf5300c0b3b350248
  11:        0x10fda4bf1 - cargo_sort_ck::main::h570d6b9dcca1a473
  12:        0x10fda0446 - std::rt::lang_start::{{closure}}::hf5e5b588b68a3ac9
  13:        0x10fe30def - std::rt::lang_start_internal::hcd84a36052901671
  14:        0x10fda4f09 - main
```

</p>
</details>

<details><summary>Cargo.toml</summary>
<p>

```toml
[package]
name = "api"
version = "0.1.0"
authors = ["Cassandra Fridkin <cass@swag.lgbt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web server
actix-web = "3.0.0-beta.3"
# Error handling
anyhow = "1"
# Rust implementation of dataloader (https://github.com/graphql/dataloader)
dataloader = { version = "0.12", default-features = false, features = ["runtime-tokio"] }
# Rust really doesn't have logging in std
log = "0.4"
# But at least we can have pretty logging
pretty_env_logger = "0.4"
# Graphql server, currently undergoing major development
# so a lot of features are only available on master
juniper = { git = "https://github.com/graphql-rust/juniper" }
# Date and time library
chrono = "0.4"
# Connection pooling for databases
r2d2 = "0.8"
# Redis, including cluster and pooling support
redis = { version = "0.17", features = ["r2d2", "cluster"] }
# Cryptographic hashing library for passwords
sodiumoxide = "0.2"
# SQL but like...in rust. Originally I was using the Diesel ORM but
# honestly I kind of hate ORMs.
# Tokio runtime, macro support, etc.
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono", "ipnetwork", "tls" ] }
# URL parsing and handling
url = "2.1"

[dev-dependencies]
# I suspect eventually I'll use this
dotenv = "0.15"
```

</p>
</details>

Any ideas on what the issue is? I suspect it's [somewhere in here](https://github.com/DevinR528/toml-parse/blob/master/src/sort/mod.rs#L70-L130), meaning this may actually be a bug with toml-parse. Thanks for your time!
